- name: create elb
  hosts: localhost
  connenction: localhost
  tasks:
   - name: elb
     ec2_elb_lb:
      name: sathishelb
      state: present
      region: ap-south-1
      cross_az_load_balancing: yes
      listeners:
        - protocol: http
          load_balance_port: 80
          instance_port: 80
      tags:
       name: sathish_elb
       security_group_ids:
       zones: ap-south-1a
      health_check: 
         ping_protocol: http
         ping_port: 80
         ping_path: "/index.html"
         response_timeout: 5
         interval: 30
         unhealthy_threshold: 2
         healthy_threshold: 2






